name: tubes_ppb
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.3.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  universal_html: ^2.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/rectangle_1.png
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/images/download_2.jpeg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/images/rectangle_1.png
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/images/info_24_dp_fill_0_wght_400_grad_0_opsz_2411.png
  - assets/images/famous_people_with_kim_jong_uns_hair_1.jpeg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/linear_arrows_action_logout_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/images/famous_people_with_kim_jong_uns_hair_1.jpeg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/images/rectangle_1.png
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/bold_video_audio_sound_camera_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_2_x2.svg

