// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTeH04TP8cwd2IThsNYaReKhz_ysNWKJw',
    appId: '1:728078343038:web:93b6fba7672f760494b12f',
    messagingSenderId: '728078343038',
    projectId: 'ecosmart-ppb-ti3-2',
    authDomain: 'ecosmart-ppb-ti3-2.firebaseapp.com',
    storageBucket: 'ecosmart-ppb-ti3-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqNGNwQ6zgAWAmlKT-EZe1HUMkvjNgDoQ',
    appId: '1:728078343038:android:adfc83e46178699094b12f',
    messagingSenderId: '728078343038',
    projectId: 'ecosmart-ppb-ti3-2',
    storageBucket: 'ecosmart-ppb-ti3-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy33nj61Ns4-ybOpPT_Q64QN7IZ-S1cds',
    appId: '1:728078343038:ios:96e0f1aed1219dfb94b12f',
    messagingSenderId: '728078343038',
    projectId: 'ecosmart-ppb-ti3-2',
    storageBucket: 'ecosmart-ppb-ti3-2.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy33nj61Ns4-ybOpPT_Q64QN7IZ-S1cds',
    appId: '1:728078343038:ios:96e0f1aed1219dfb94b12f',
    messagingSenderId: '728078343038',
    projectId: 'ecosmart-ppb-ti3-2',
    storageBucket: 'ecosmart-ppb-ti3-2.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTeH04TP8cwd2IThsNYaReKhz_ysNWKJw',
    appId: '1:728078343038:web:c1bbd79e19e4902794b12f',
    messagingSenderId: '728078343038',
    projectId: 'ecosmart-ppb-ti3-2',
    authDomain: 'ecosmart-ppb-ti3-2.firebaseapp.com',
    storageBucket: 'ecosmart-ppb-ti3-2.appspot.com',
  );
}
